### ISSUE TITLE
Modelo do ./ConfigFirefase

### ISSUE THREAD

**Issue by licensed** [victorsouzadev/lista-de-presentes-casamento#1]
Tentei rodar aqui mas não achou o ./ConfigFirebase
Module not found: Can't resolve './ConfigFirebase' in '/home/licensed/gitz/lista-de-presentes-casamento/src'

**Comment by victorsouzadev** [comment]
O arquivo `./ConfigFirebase`  exporta um objeto (como na imagem abaixo) com as configurações do projeto que deve ser criado no Firebase. Por se tratar das configurações do Realtime Database decidi manter esse arquivo no `.gitignore`.

![configDatabase](https://user-images.githubusercontent.com/25651037/95080807-0a054500-06ef-11eb-9b2a-db62ad512f8c.png)

Esse objeto também pode ser passado para a função `firebase.initializeApp()` no arquivo `./Firebase.js`.

**Comment by victorsouzadev** [comment]
Um exemplo desse arquivo no projeto:

![cofigDatabaseProject](https://user-images.githubusercontent.com/25651037/95082454-69fceb00-06f1-11eb-80f6-0e8e14136aa5.png)

**Comment by licensed** [comment]
Aqui funcionou. Obrigado!
